import {  Rubik, Lato } from "next/font/google";
import "./globals.css";
import Header from "./components/TopBar/Header";
import Navbar from "./components/TopBar/Navbar";
import HealthcareFooter from "./components/Footer/HealthcareFooter ";


const rubik = Rubik({
  variable: "--font-rubik",
  subsets: ["latin"],
  display: "swap",
});


const lato = Lato({
  variable: "--font-lato",
  subsets: ["latin"],
  weight: ["400", "700"],
  display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${rubik.variable} ${lato.variable}`}>
      <body className="antialiased">
        <Header />
        <Navbar />
        {children}
        <HealthcareFooter/>
      </body>
    </html>
  );
}

